#!/bin/bash
#
#SBATCH --job-name chi-neu
#SBATCH --output output.log
#SBATCH --partition  batch1
#SBATCH --nodes 1 
#SBATCH --ntasks-per-node 8
#SBATCH --time 24:00:00

# set directory with inputs, must be the full path without /home/username
startdir=$SLURM_SUBMIT_DIR

cd ${startdir}


#exe=/shared/dressler/chi/CPMD_okt_2017/CPMD-CHI/BINPAR/cpmd.x
exe=/home/dressler/post_doc/programs/CPMD-CHI/BINPAR/cpmd.x
pps=/net/shared/dressler/cpmd/potentials

run=wfo
rm GEOMETRY* LATEST RESTART.1 $run.err $run.out *wan
mpirun $exe $run.inp $pps 1>> $run.out 2>> $run.err

/home/dressler/post_doc/programs/cpmd4/v2/cpmd2cube/cpmd2cube.x -fullmesh -o DENSITY_fullmesh -dens DENSITY > out_fullmesh.cpmd2cube_old
#/home/dressler/post_doc/programs/cpmd4/cpmd2cube/cpmd2cube.x -fullmesh -o DENSITY_fullmesh -dens DENSITY > out_fullmesh.cpmd2cube_old
