#!/bin/bash
#mpirun /shared/dressler/chi/CPMD_okt_2017/CPMD-CHI/BINPAR/cpmd.x  wfo.inp /shared/dressler/cpmd/potentials > neu_compiliert
#exe=/net/shared/dressler/chi/CPMD_okt_2017/CPMD-CHI/BINPAR/cpmd.x
exe=/home/dressler/post_doc/programs/CPMD-CHI/BINPAR/cpmd.x

pps=/net/shared/dressler/cpmd/potentials

run=wfo
rm GEOMETRY* LATEST RESTART.1 $run.err $run.out
mpirun -n 4 $exe $run.inp $pps 1>> $run.out 2>> $run.err
mv RESTART.1 WFO-RESTART
mv GEOMETRY.xyz WFO-GEOMETRY.xyz
cp WFO-RESTART RESTART

/home/dressler/post_doc/programs/cpmd4/v2/cpmd2cube/cpmd2cube.x -fullmesh -o DENSITY_fullmesh -dens DENSITY > out_fullmesh.cpmd2cube_old
#/home/dressler/post_doc/programs/cpmd4/cpmd2cube/cpmd2cube.x -fullmesh -o DENSITY_fullmesh -dens DENSITY > out_fullmesh.cpmd2cube_old
